# Generated by Django 3.2.5 on 2021-08-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210730_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
