# Generated by Django 3.2.5 on 2021-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_loja_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='status',
            field=models.CharField(choices=[('S', 'Aberto'), ('N', 'Fechado')], default='Aberto', max_length=1),
        ),
    ]
