# Generated by Django 3.2.5 on 2021-08-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_loja_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='status',
            field=models.CharField(choices=[('Aberto', 'A'), ('Fechado', 'F')], default='Aberto', max_length=7),
        ),
    ]
