# Generated by Django 3.2.5 on 2021-09-01 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_carrinho_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.endereco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='latitude',
            field=models.FloatField(default=32.2),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='longitude',
            field=models.FloatField(default=32.3),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
