# Generated by Django 3.2.5 on 2021-09-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210901_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.loja'),
            preserve_default=False,
        ),
    ]
