# Generated by Django 3.2.5 on 2021-09-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_produto_disponivel'),
        ('main', '0014_auto_20210913_1427'),
    ]

    operations = [
    ]
